name: CI Pipeline
on: [push]  #Запуск при push в репозиторий

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
      
      - name: Use Node.js
        run: npm run test
  
