name: CI Pipeline
on: [push]  #Запуск при push в репозиторий

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install
      
      - name: Use Node.js
        run: npm run test

      - name: Run linter
        run: npm run lint
